/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AiImageRouteImport } from './routes/ai-image'
import { Route as AiVideoGeneratorRouteImport } from './routes/ai-video-generator'
import { Route as ApidotMediaRouteImport } from './routes/apidot-media'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlankRouteImport } from './routes/blank'
import { Route as CharacterSwapRouteImport } from './routes/character-swap'
import { Route as ImageToVideoRouteImport } from './routes/image-to-video'
import { Route as MultiSceneRouteImport } from './routes/multi-scene'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ApiPublicVideoProxyRouteImport } from './routes/api/public/video-proxy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AiImageRoute = AiImageRouteImport.update({
  id: '/ai-image',
  path: '/ai-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVideoGeneratorRoute = AiVideoGeneratorRouteImport.update({
  id: '/ai-video-generator',
  path: '/ai-video-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApidotMediaRoute = ApidotMediaRouteImport.update({
  id: '/apidot-media',
  path: '/apidot-media',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterSwapRoute = CharacterSwapRouteImport.update({
  id: '/character-swap',
  path: '/character-swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToVideoRoute = ImageToVideoRouteImport.update({
  id: '/image-to-video',
  path: '/image-to-video',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiSceneRoute = MultiSceneRouteImport.update({
  id: '/multi-scene',
  path: '/multi-scene',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideoProxyRoute = ApiPublicVideoProxyRouteImport.update({
  id: '/api/public/video-proxy',
  path: '/api/public/video-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-image': typeof AiImageRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/apidot-media': typeof ApidotMediaRoute
  '/auth': typeof AuthRoute
  '/blank': typeof BlankRoute
  '/character-swap': typeof CharacterSwapRoute
  '/image-to-video': typeof ImageToVideoRoute
  '/multi-scene': typeof MultiSceneRoute
  '/payments': typeof PaymentsRoute
  '/voice': typeof VoiceRoute
  '/api/public/video-proxy': typeof ApiPublicVideoProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-image': typeof AiImageRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/apidot-media': typeof ApidotMediaRoute
  '/auth': typeof AuthRoute
  '/blank': typeof BlankRoute
  '/character-swap': typeof CharacterSwapRoute
  '/image-to-video': typeof ImageToVideoRoute
  '/multi-scene': typeof MultiSceneRoute
  '/payments': typeof PaymentsRoute
  '/voice': typeof VoiceRoute
  '/api/public/video-proxy': typeof ApiPublicVideoProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-image': typeof AiImageRoute
  '/ai-video-generator': typeof AiVideoGeneratorRoute
  '/apidot-media': typeof ApidotMediaRoute
  '/auth': typeof AuthRoute
  '/blank': typeof BlankRoute
  '/character-swap': typeof CharacterSwapRoute
  '/image-to-video': typeof ImageToVideoRoute
  '/multi-scene': typeof MultiSceneRoute
  '/payments': typeof PaymentsRoute
  '/voice': typeof VoiceRoute
  '/api/public/video-proxy': typeof ApiPublicVideoProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai-image'
    | '/ai-video-generator'
    | '/apidot-media'
    | '/auth'
    | '/blank'
    | '/character-swap'
    | '/image-to-video'
    | '/multi-scene'
    | '/payments'
    | '/voice'
    | '/api/public/video-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai-image'
    | '/ai-video-generator'
    | '/apidot-media'
    | '/auth'
    | '/blank'
    | '/character-swap'
    | '/image-to-video'
    | '/multi-scene'
    | '/payments'
    | '/voice'
    | '/api/public/video-proxy'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ai-image'
    | '/ai-video-generator'
    | '/apidot-media'
    | '/auth'
    | '/blank'
    | '/character-swap'
    | '/image-to-video'
    | '/multi-scene'
    | '/payments'
    | '/voice'
    | '/api/public/video-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AiImageRoute: typeof AiImageRoute
  AiVideoGeneratorRoute: typeof AiVideoGeneratorRoute
  ApidotMediaRoute: typeof ApidotMediaRoute
  AuthRoute: typeof AuthRoute
  BlankRoute: typeof BlankRoute
  CharacterSwapRoute: typeof CharacterSwapRoute
  ImageToVideoRoute: typeof ImageToVideoRoute
  MultiSceneRoute: typeof MultiSceneRoute
  PaymentsRoute: typeof PaymentsRoute
  VoiceRoute: typeof VoiceRoute
  ApiPublicVideoProxyRoute: typeof ApiPublicVideoProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-image': {
      id: '/ai-image'
      path: '/ai-image'
      fullPath: '/ai-image'
      preLoaderRoute: typeof AiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-video-generator': {
      id: '/ai-video-generator'
      path: '/ai-video-generator'
      fullPath: '/ai-video-generator'
      preLoaderRoute: typeof AiVideoGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apidot-media': {
      id: '/apidot-media'
      path: '/apidot-media'
      fullPath: '/apidot-media'
      preLoaderRoute: typeof ApidotMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank': {
      id: '/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-swap': {
      id: '/character-swap'
      path: '/character-swap'
      fullPath: '/character-swap'
      preLoaderRoute: typeof CharacterSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-video': {
      id: '/image-to-video'
      path: '/image-to-video'
      fullPath: '/image-to-video'
      preLoaderRoute: typeof ImageToVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-scene': {
      id: '/multi-scene'
      path: '/multi-scene'
      fullPath: '/multi-scene'
      preLoaderRoute: typeof MultiSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video-proxy': {
      id: '/api/public/video-proxy'
      path: '/api/public/video-proxy'
      fullPath: '/api/public/video-proxy'
      preLoaderRoute: typeof ApiPublicVideoProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AiImageRoute: AiImageRoute,
  AiVideoGeneratorRoute: AiVideoGeneratorRoute,
  ApidotMediaRoute: ApidotMediaRoute,
  AuthRoute: AuthRoute,
  BlankRoute: BlankRoute,
  CharacterSwapRoute: CharacterSwapRoute,
  ImageToVideoRoute: ImageToVideoRoute,
  MultiSceneRoute: MultiSceneRoute,
  PaymentsRoute: PaymentsRoute,
  VoiceRoute: VoiceRoute,
  ApiPublicVideoProxyRoute: ApiPublicVideoProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
